In [49]:
# basic imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df_1 = pd.read_csv("scraped_steam_games.csv")
df_1.head()
#each csv is around 500 games long, will have to concatenate into one big dataframe

,Name,Release Date,Price,Discount,Developer,Publisher,Total Reviews,Positive Reviews,Negative Reviews,Review Sentiment,Genre(s)
0,Counter-Strike 2,"Aug 21, 2012",Free To Play,No Discount,Valve,Valve,"9,767,142","8,401,470","1,365,672",Mostly Positive,"['Action', 'Free To Play']"
1,Palworld,"Jul 9, 2026",$251.18,$53.98,Pocketpair,Pocketpair,"466,128","440,315","25,813",Very Positive,"['Action', 'Adventure', 'Indie', 'RPG']"
2,Baldur's Gate 3,"Aug 3, 2023",$59.99,$41.99,Larian Studios,Larian Studios,"850,775","823,465","27,310",Very Positive,"['Adventure', 'RPG', 'Strategy']"
3,Marvel Rivals,"Dec 5, 2024",Free To Play,No Discount,NetEase Games,NetEase Games,"405,407","307,754","97,653",Mixed,"['Action', 'Free To Play']"
4,Warframe,"Mar 25, 2013",$1.99,$1.59,Digital Extremes,Digital Extremes,"678,882","593,641","85,241",Very Positive,"['Action', 'RPG', 'Free To Play']"

In [51]:
df_2 = pd.read_csv("scraped_steam_games_2.csv")
df_2.head()

,Name,Release Date,Price,Discount,Developer,Publisher,Total Reviews,Positive Reviews,Negative Reviews,Review Sentiment,Genre(s)
0,shapez 2 - Factory,"Apr 23, 2026",$29.99,$17.99,tobspr Games,tobspr Games,"14,985","14,546",439,Very Positive,"['Casual', 'Indie', 'Simulation', 'Strategy']"
1,Blue Archive,"Jul 3, 2025",Free To Play,No Discount,NEXON Games,NEXON Korea,"27,467","17,836","9,631",Overwhelmingly Negative,"['Adventure', 'Casual', 'RPG', 'Strategy']"
2,DRAGON BALL GEKISHIN SQUADRA,"Sep 9, 2025",Free To Play,No Discount,"GANBARION Co., Ltd.",Bandai Namco Entertainment,"10,606","6,904","3,702",Mixed,"['Action', 'Free To Play']"
3,Infection Free Zone,"Apr 11, 2024",$44.98,$17.31,Jutsu Games,Games Operators,"18,349","14,784","3,565",Very Positive,"['Action', 'Indie', 'Simulation', 'Strategy']"
4,Soul Land: Awakening World,"Jun 1, 2026",Free To Play,No Discount,37GAMES,37GAMES,348,167,181,Mixed,"['Action', 'Adventure', 'Massively Multiplayer..."

In [52]:
#concat the two dataframes together
df = pd.concat([df_1, df_2])
print(df.shape)

(996, 11)

# Data Cleaning

In [53]:
#go feature by feature
#date parse
df["Release Date"] = pd.to_datetime(df["Release Date"], format = "mixed")
print(df["Release Date"])

0     2012-08-21
1     2026-07-09
2     2023-08-03
3     2024-12-05
4     2013-03-25
         ...
495   2026-01-27
496   2025-06-17
497   2025-09-08
498   2025-02-13
499   2021-04-08
Name: Release Date, Length: 996, dtype: datetime64[us]

In [66]:
#price
df["Price"] = df["Price"].replace("Free To Play", "0")
df["Price"] = df["Price"].replace("No Price", "0")
df["Price"] = df["Price"].str.strip("$")
df["Price"].astype("float")

ValueError: could not convert string to float: 'Factorio Demo'